# -*- coding: utf-8 -*-
"""Sales Dashboard

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Onolo-oOn7GbWR5nGqFrdMO6uz9NMr0O

Install Libraries
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="whitegrid")

"""Load Dataset"""

import pandas as pd
from google.colab import files

# pilih file dari device
uploaded = files.upload()

# ambil nama file yang dipilih
file_name = list(uploaded.keys())[0]

# load ke pandas
df = pd.read_excel(file_name)

# lihat data
df.head()

"""Data Preparation"""

# Standardize column names (optional but clean)
df.columns = df.columns.str.strip()

# Example expected columns:
# Month, Brand, Branch, Revenue, GA, Subscriber, Sell In

# Convert month to datetime if needed
df["Month"] = pd.to_datetime(df["Month"], errors='coerce')

"""Create KPI"""

total_revenue = df["Revenue"].sum()
total_ga = df["GA"].sum()
total_subscriber = df["Subscribers"].sum()
total_sellin = df["Sell_In"].sum()

# ARPU = Revenue / Subscriber
arpu = total_revenue / total_subscriber

print("ARPU:", arpu)

"""Aggregate"""

# Trend
trend = df.groupby("Month")["Revenue"].sum()

# By Brand
revenue_brand = df.groupby("Brand")["Revenue"].sum()
subscriber_brand = df.groupby("Brand")["Subscribers"].sum()
arpu_brand = revenue_brand / subscriber_brand

# By Branch
sellin_branch = df.groupby("Branch")["Sell_In"].sum()
revenue_branch = df.groupby("Branch")["Revenue"].sum()
ga_branch = df.groupby("Branch")["GA"].sum()

"""Build Dashboard"""

fig = plt.figure(figsize=(18,10))
gs = fig.add_gridspec(3,4)

# ---------------------------
# KPI BOXES (Top Row)
# ---------------------------
fig.text(0.1,0.92,f"ARPU\n{arpu:,.0f}", fontsize=12, bbox=dict(facecolor='#d9edf7'))
fig.text(0.25,0.92,f"Revenue\n{total_revenue/1e9:.1f} B", fontsize=12, bbox=dict(facecolor='#d9edf7'))
fig.text(0.4,0.92,f"GA\n{total_ga:,.0f}", fontsize=12, bbox=dict(facecolor='#d9edf7'))
fig.text(0.55,0.92,f"Subscriber\n{total_subscriber:,.0f}", fontsize=12, bbox=dict(facecolor='#d9edf7'))
fig.text(0.7,0.92,f"Sell In\n{total_sellin:,.0f}", fontsize=12, bbox=dict(facecolor='#d9edf7'))

# ---------------------------
# ARPU Trend
# ---------------------------
ax1 = fig.add_subplot(gs[0,0:3])
trend.plot(ax=ax1)
ax1.set_title("ARPU / Revenue Trend")

# ---------------------------
# Pie Charts
# ---------------------------
ax2 = fig.add_subplot(gs[0,3])
subscriber_brand.plot(kind="pie", autopct="%1.0f%%", ax=ax2)
ax2.set_title("Subscribers by Brand")

ax3 = fig.add_subplot(gs[1,3])
arpu_brand.plot(kind="pie", autopct="%1.0f%%", ax=ax3)
ax3.set_title("ARPU by Brand")

# ---------------------------
# Revenue by Brand
# ---------------------------
ax4 = fig.add_subplot(gs[1,0:3])
revenue_brand.plot(kind="bar", ax=ax4)
ax4.set_title("Revenue by Brand")

# ---------------------------
# Sell In by Branch
# ---------------------------
ax5 = fig.add_subplot(gs[2,0])
sellin_branch.sort_values().plot(kind="barh", ax=ax5)
ax5.set_title("Sell In by Branch")

# ---------------------------
# Revenue by Branch
# ---------------------------
ax6 = fig.add_subplot(gs[2,1])
revenue_branch.sort_values().plot(kind="barh", ax=ax6)
ax6.set_title("Revenue by Branch")

# ---------------------------
# GA by Branch
# ---------------------------
ax7 = fig.add_subplot(gs[2,2])
ga_branch.sort_values().plot(kind="barh", ax=ax7)
ax7.set_title("GA by Branch")

plt.suptitle("Sales KPI Productivity Dashboard", fontsize=18)

plt.tight_layout()
plt.show()